name: Build and Release Binary
on:
  push:
    branches: [master, build_*]
    tags: [v*]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: ubuntu-latest
            gcc_arch: gcc
          - arch: arm64
            runs-on: ubuntu-latest-arm64
            gcc_arch: gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev libevent-dev libbsd-dev
      - name: Build binary
        run: |
          make CC=${{ matrix.gcc_arch }}
          mv ustreamer ustreamer-${{ matrix.arch }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ustreamer-${{ matrix.arch }}
          path: ustreamer-${{ matrix.arch }}
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ustreamer-*/ustreamer-*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}