name: Build and Release Binary
on:
  push:
    branches: [master, build_*]
    tags: [v*]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dockcross/linux-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add repositories
        run: |
          echo "deb http://deb.debian.org/debian bullseye main contrib non-free" >> /etc/apt/sources.list
          echo "deb http://security.debian.org/debian-security bullseye-security main contrib non-free" >> /etc/apt/sources.list
          echo "deb http://deb.debian.org/debian bullseye-updates main contrib non-free" >> /etc/apt/sources.list
      - name: Install libraries
        run: |
          dpkg --add-architecture arm64
          apt-get update
          apt-get install -y --no-install-recommends \
              libjpeg-turbo-dev:arm64 \
              libjpeg8-dev:arm64 \
              libbsd-dev:arm64 \
              libgpiod-dev:arm64
      - name: Build
        run: |
          make
          ls -lisa .
          mv ustreamer ustreamer-arm64
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ustreamer-arm64
          path: ustreamer-arm64
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ustreamer-*/ustreamer-*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}