name: Build and Release Binary
on:
  push:
    branches: [master, build_*]
    tags: [v*]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: ubuntu-20.04
            gcc_arch: gcc
          - arch: arm64
            runs-on: ubuntu-20.04
            gcc_arch: aarch64-linux-gnu-gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure ARM64 repositories
        if: matrix.arch == 'arm64'
        run: |
          sudo dpkg --add-architecture arm64
          echo "deb [arch=arm64] http://archive.raspbian.org/raspbian bullseye main" | sudo tee /etc/apt/sources.list.d/raspbian.list
          curl -sSL https://archive.raspbian.org/raspbian.public.key | sudo apt-key add -
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev libevent-dev libbsd-dev
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
            sudo apt-get install -y crossbuild-essential-arm64
            sudo apt-get install -y libjpeg-dev:arm64 libevent-dev:arm64 libbsd-dev:arm64
          fi
      - name: Build binary
        run: |
          make CC=${{ matrix.gcc_arch }}
          mv ustreamer ustreamer-${{ matrix.arch }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ustreamer-${{ matrix.arch }}
          path: ustreamer-${{ matrix.arch }}
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ustreamer-*/ustreamer-*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}