name: Build Alpine

on:
    push:
        tags: [v*]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master
      -
        name: Build and export artifacts
        uses: docker/build-push-action@v3
        with:
          context: .
          outputs: type=local,dest=./build
          file: pkg/docker/Dockerfile.alpine
      -
        name: Test
        run: |
          echo version: $(docker run --rm -t ustreamer --version)
          echo -e "features:\n$(docker run --rm -t ustreamer --features)"
      -
        name: Build multi arch
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          outputs: type=local,dest=./build-multiarch
          file: pkg/docker/Dockerfile.alpine

      - 
        name: Rename local file for match architecture
        run: |
          mv ./build-multiarch/linux_arm64/ustreamer/ustreamer ./build-multiarch/linux_arm64/ustreamer/ustreamer-arm64
          mv ./build-multiarch/linux_amd64/ustreamer/ustreamer ./build-multiarch/linux_amd64/ustreamer/ustreamer-amd64
          mv ./build-multiarch/linux_arm_v7/ustreamer/ustreamer ./build-multiarch/linux_arm_v7/ustreamer/ustreamer-armv7
          mv ./build-multiarch/linux_arm_v6/ustreamer/ustreamer ./build-multiarch/linux_arm_v6/ustreamer/ustreamer-armv6
      -
        name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: rctelemetrie (ARMv7)
          files: |
            ./build-multiarch/linux_arm64/ustreamer/ustreamer-arm64
            ./build-multiarch/linux_amd64/ustreamer/ustreamer-amd64
            ./build-multiarch/linux_arm_v7/ustreamer/ustreamer-armv7
            ./build-multiarch/linux_arm_v6/ustreamer/ustreamer-armv6
          fail_on_unmatched_files: true
          token: ${{ secrets.GH_TOKEN }}
