name: Build Alpine

on:
    push:
        branches: [master, build_*]
        tags: [v*]
    pull_request:
        branches: [master]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_REPO }}/ustreamer,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            ghcr.io/${{ github.repository }},enable=${{ github.event_name != 'pull_request' }}
          tags: |
            type=ref,event=tag
            type=sha,format=long
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ustreamer
          file: pkg/docker/Dockerfile.alpine
      -
        name: Test
        run: |
          echo version: $(docker run --rm -t ustreamer --version)
          echo -e "features:\n$(docker run --rm -t ustreamer --features)"
      -
        name: Build multi arch
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          file: pkg/docker/Dockerfile.alpine
          tags: ustreamer-multiarch
      -
        name: Extract binaries
        run: |
          for platform in "linux/amd64" "linux/arm64" "linux/arm/v7" "linux/arm/v6"; do
            echo "Extracting for $platform"
            
            arch=$(echo $platform | cut -d/ -f2)
            variant=$(echo $platform | cut -d/ -f3)
            
            if [ -n "$variant" ]; then
              filename="ustreamer-linux-${arch}-${variant}"
            else
              filename="ustreamer-linux-${arch}"
            fi
            
            container_id=$(docker create --platform $platform ustreamer-multiarch)
            mkdir -p dist
            docker cp $container_id:/usr/local/bin/ustreamer "dist/$filename"
            docker rm $container_id
          done
          
          cd dist
          for binary in *; do
            tar czf "$binary.tar.gz" "$binary"
            rm "$binary"
          done
      -
        name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
